USE quizduell;

ALTER TABLE USER ADD CONSTRAINT USER_AVATARID_AVATAR_AVATARID
    FOREIGN KEY (AVATAR_ID) REFERENCES AVATAR(AVATAR_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE BELONG ADD CONSTRAINT BELONG_QUESTIONID_QUESTION_QUESTIONID
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE BELONG ADD CONSTRAINT BELONG_GAMEID_GAME_GAMEID
    FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE PLAY ADD CONSTRAINT PLAY_USERID_USER_USERID
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

ALTER TABLE PLAY ADD CONSTRAINT PLAY_GAMEID_GAME_GAMEID
    FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;